// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const clues_treasure: string[] = [
  "a key on a blue ribbon",
  "a jar of glowing honey",
  "a folded map with an X and no legend",
  "a tiny compass that spins when near water",
  "a small carved bear that feels warm",
  "a ring that hums softly in the dark",
  "a handkerchief with initials stitched inside",
  "a coin with an unknown monarch's face",
  "a glass bead that shows a different scene when tilted",
  "a pressed flower with a note about the date",
  "a lock of white hair tied in a bow",
  "a flat stone with a perfect handprint",
  "a music box that plays a tune nobody recognizes",
  "a small book with every other page torn out",
  "a pair of spectacles that show writing on bark",
  "a pouch of seeds nobody can identify",
  "a wax seal broken in a specific shape",
  "a feather that never gets wet",
  "a whistle that only dogs and foxes hear",
  "a brass button from a warden's coat",
  "a rolled-up receipt for something unusual",
  "a comb with a missing tooth and someone's hair in it",
  "a lantern that burns without oil",
  "a letter that begins mid-sentence",
  "a hollow acorn filled with dried lavender",
  "a child's drawing of a door no one has seen yet",
];
