// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const complications: string[] = [
  "gear gets soggy",
  "a friend wanders off",
  "the path loops back",
  "someone twists their ankle",
  "the lantern runs low on oil",
  "a sudden rain soaks everyone's packs",
  "the bridge is much weaker than it looks",
  "a helpful creature turns out to be an obstacle",
  "the map is wrong",
  "night falls faster than expected",
  "the rope frays at the worst moment",
  "someone loses their most important item",
  "a locked door stands between the group and the goal",
  "what the group needs is already taken",
  "someone in the group is too scared to move",
  "the easiest route is blocked by a tree fall",
  "the key to the puzzle is missing a piece",
  "the weather changes and makes travel harder",
  "another group of travelers wants the same thing",
  "the creature is friendly but won't stop following",
  "the shortcut is longer than the long way",
  "a helpful stranger has the wrong directions",
  "the door opens outward instead of inward",
  "the clue points somewhere the group just left",
  "a tool breaks at the worst time",
  "someone needs to rest and cannot continue yet",
  "an unexpected noise startles everyone into hiding",
  "the item wanted is guarded by someone asleep",
  "the way forward requires getting very muddy",
  "a riddle must be solved before anything else works",
  "the creature only speaks in rhyme",
  "the path splits three ways with no signs",
  "a fence too high to climb easily",
  "the group must split up",
  "a witness refuses to talk until fed",
  "daylight is fading and the only torch is damp",
  "the thing the group seeks has moved",
  "the forest floor is unexpectedly boggy",
  "one group member is carrying too much",
  "the noise draws unwanted attention",
  "the passage is too small for everyone",
  "the reward is real but difficult to carry",
  "the agreement turns out to be a misunderstanding",
  "the shortcut runs through someone's home without permission",
  "the correct answer causes a new problem",
  "the guide falls asleep mid-journey",
  "the group's packs snag on thorns",
  "the fog makes it easy to walk in circles",
  "the creature blocking the path is just lonely",
  "the only way down is a slide they can't climb back up",
  "an old promise resurfaces at the worst time",
];
