// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const names: string[] = [
  "Hazel-Anne",
  "Old Mossback",
  "Briar",
  "Fennick",
  "Wren",
  "Aldric the Younger",
  "Thistle",
  "Sorrel",
  "Juniper",
  "Cob",
  "Meadowbell",
  "Tallow",
  "Griselda",
  "Pipwick",
  "Rowan",
  "Nutkin",
  "Brambleby",
  "Frosina",
  "Corvin",
  "Sage",
  "Elsinwood",
  "Tuck",
  "Dimmock",
  "Lark",
  "Vesper",
  "Clover",
];
