// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const npc_traits: string[] = [
  "gruff but secretly kind",
  "speaks only in questions",
  "always eating something",
  "collects unusual hats",
  "laughs at the wrong moments",
  "very tall and apologizes for it constantly",
  "forgets names but remembers every face",
  "whispers everything as if sharing a secret",
  "has an opinion about every type of mushroom",
  "carries a map that is never quite right",
  "hums while thinking",
  "startles easily but recovers fast",
  "very proud of a scar from a boring accident",
  "sleepy by day, wide awake after dark",
  "extremely polite even when angry",
  "can't walk in a straight line",
  "has three scarves on at all times",
  "gives unsolicited advice about weather",
  "holds grudges about card games",
  "narrates what they're doing while they do it",
  "afraid of doors that open the wrong way",
  "apologizes to furniture they bump into",
  "very suspicious of birds",
  "winks after every sentence, even sad ones",
  "claims to have met a giant once",
  "extremely good at standing perfectly still",
];
