// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const npc_wants: string[] = [
  "find her lost sheep",
  "sell turnips",
  "get a letter delivered",
  "borrow a lantern before dark",
  "have someone sit with them while they rest",
  "know if the road ahead is safe",
  "find their runaway goat",
  "return a borrowed hat",
  "hear a joke they haven't heard before",
  "trade an unusual stone for bread",
  "reach the mill before it closes",
  "warn a friend about the weather",
  "find a good campsite before nightfall",
  "have someone read a sign aloud",
  "get help crossing a muddy patch",
  "reclaim something taken by a crow",
  "find someone to share a fire",
  "trade a cloak for directions",
  "pass on a message about the market",
  "have someone taste their soup",
  "know which path leads to the Hollow Oak",
  "find the person who left a bag behind",
  "get home before the rain",
  "share news about what they saw on the road",
  "have someone carry something heavy a short distance",
  "find out if the old bridge is safe",
];
