// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const omens_weather: string[] = [
  "sudden warm fog",
  "crows flying backward",
  "first snow of the season",
  "a rain that smells of cinnamon",
  "the sun sets twice in one evening",
  "a rainbow at midnight",
  "all the birds go silent at once",
  "the stream runs uphill for an hour",
  "a heavy dew that tastes sweet",
  "three shooting stars in a row",
  "the trees all lean east as if listening",
  "a thunderstorm with no rain",
  "frost on the grass but not on the leaves",
  "fireflies appear at noon",
  "the wind carries someone's name",
  "a circle of fog around the moon",
  "hail the size of acorns falls briefly",
  "the shadows all point the wrong way",
  "a warm breeze in the middle of winter",
  "snow that falls upward in one small patch",
  "a mist that glows faintly blue",
  "the puddles freeze in unusual patterns",
  "clouds shaped like animals drift very slowly",
  "an unseasonal burst of wildflowers",
  "the sky turns amber for ten minutes",
  "a gentle rain stops and starts every few minutes",
  "lightning with no thunder",
  "a morning fog that hums softly",
  "the air smells of bread and pine",
  "dew forms in perfect circles on flat stones",
  "a single sunbeam breaks through dense clouds",
  "birds land and refuse to fly for an hour",
  "wind chimes ring with no wind",
  "leaves fall up before settling down",
  "a perfectly still day in every direction",
  "thick ice forms on the pond overnight",
  "the fog hangs only waist-high",
  "a warm spell that lasts only one afternoon",
  "the mud hardens overnight with no frost",
  "bees swarm one tree and leave at dusk",
  "a distant drumming from the hills",
  "the brook turns a soft violet for a few minutes",
  "spiderwebs cover everything at dawn",
  "the wind shifts direction every few steps",
  "heavy purple clouds that never quite rain",
  "the full moon appears in daytime",
  "icicles form on warm branches",
  "a faint aurora on a mild evening",
  "the path feels slightly warmer than the surrounding grass",
  "frogs singing in mid-winter",
  "the stars are reflected in dry grass blades",
];
