// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const scene_seeds: string[] = [
  "a bridge that asks a riddle before you can cross",
  "a sheep stuck in brambles",
  "a crying child sitting beside a locked box",
  "an old signpost pointing four ways with all signs broken",
  "a market stall with nobody tending it",
  "a giant sleeping creature blocking the path",
  "a trail of feathers leading into the dark",
  "a door in the middle of a field with no building around it",
  "a boat bumping against the shore with no one aboard",
  "a fire burning in a clearing with a full pot and no cook",
  "a note nailed to a tree in an unknown script",
  "a hole in the ground with a warm glow below",
  "a fox who tries to give the group a ring",
  "a strange tower that wasn't there yesterday",
  "a talking tree that has forgotten how to stop talking",
  "a bag of letters with no addresses",
  "an old woman selling soup that tastes like memories",
  "a wounded bird wearing a tiny crown",
  "a barrel rolling slowly uphill by itself",
  "a map drawn on a leaf pointing to the center of the Wood",
  "a pair of boots walking with no feet inside",
  "a well that whispers names when you lean over it",
  "a hedgehog carrying a lantern and muttering about being late",
  "a rope ladder dangling from the clouds",
  "a child's bedroom recreated under a big oak",
  "a giant spider spinning a web shaped like a story",
  "two ghosts arguing about who left the gate open",
  "a wooden chest buried to its lid, rattling",
  "a crowd of tiny people building a very small bridge",
  "a waterfall frozen mid-fall",
  "a jar of fireflies set at a crossroads",
  "a pie cooling on a windowsill with no cottage near",
  "a goat wearing a scarf who says she was a warden once",
  "a key hanging from a branch with no lock in sight",
  "a river that only flows at night",
  "a letter addressed to someone the group just met",
  "a singing stone that draws animals toward it",
  "a cloak hanging on a bare branch, still moving in the wind",
  "a table set for dinner in the middle of the Wood",
  "a mirror propped against a tree showing a different season",
  "a trail of coins leading somewhere important",
  "a very tall fox staring at a shorter fox who stares back",
  "a mushroom circle that hums at certain hours",
  "a library built into a hillside, door ajar",
  "a storm lantern with a tiny figure waving inside",
  "a child crying because their shadow went missing",
  "a signpost that changes which direction it points",
  "a warm cellar door in the middle of a forest path",
  "a hermit's workshop still running with no hermit around",
  "a sleeping giant curled in a meadow",
  "a crown resting on a fencepost with no owner nearby",
];
