// CC-BY-SA 4.0 — adapted from Cairn 2e (Yochai Gal) plus original kid-soft entries.
export const wood_locations: string[] = [
  "the Hollow Oak",
  "the Mushroom Market",
  "the Quiet Pond",
  "a leaning watchtower",
  "the Singing Bridge",
  "a cottage made of moss",
  "the Lantern Glade",
  "a fox's burrow",
  "the Crooked Mill",
  "a grove of silver birches",
  "the Frozen Waterfall",
  "a badger's underground library",
  "the Willow Arch",
  "a hidden shepherd's hut",
  "the Misty Crossing",
  "a ring of standing stones",
  "the Old Beekeeper's Ruin",
  "the Beetle Market",
  "a sunken garden full of ferns",
  "the Owl Tower",
  "a hill with a single twisted tree",
  "the Moonlit Clearing",
  "a rope bridge over a ravine",
  "the Abandoned Hermit's Cave",
  "a brook with stepping-stones",
  "the Thornwall Hedge",
  "a hollow log wide enough to walk through",
  "the Firefly Meadow",
  "a crumbled stone archway",
  "the Whispering Reeds",
  "an ancient apple orchard",
  "the Mossy Staircase",
  "a pool that shows the sky at night",
  "the Three-Sisters Pine Cluster",
  "a sunken road lined with ivy",
  "the Gnarled Root Maze",
  "a windmill missing its sails",
  "the Amber Grotto",
  "a dried-up riverbed full of smooth pebbles",
  "the Fox-Gate Inn",
  "a meadow where the grass grows in spirals",
  "the Briar Archway",
  "a cliff ledge with a cave beneath",
  "the Heather Plateau",
  "a well with a broken bucket",
  "the Crow Rookery",
  "a sunken cathedral of roots",
  "the Verdant Ramp",
  "a hill village perched on stilts",
  "the Glimmering Saltflat",
  "a crumbling watchtower covered in vines",
  "the Hedge Witch's Garden",
];
